### ISSUE TITLE
motedan テーブル定義書(2020/11/05時点)

### ISSUE THREAD

**Issue by NakasaiHayato** [NakasaiHayato/motedan#22]
![motedan_table (1)](https://user-images.githubusercontent.com/55226906/98231757-2ae7e100-1fa0-11eb-8e65-a5850442e6fa.jpg)

**Comment by ttrweb** [comment]
バイト数の部分使ってないなら削除しましょう

**Comment by ttrweb** [comment]
Usersテーブルの nickname カラム name で良いと思います
役割はニックネームにして
